# Generated by Django 2.0.5 on 2018-10-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JUnit',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=250)),
                ('package_name', models.CharField(max_length=250)),
                ('body', models.TextField()),
            ],
        ),
    ]
