# Generated by Django 2.0.5 on 2018-10-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
